# Generated by Django 4.2.7 on 2023-11-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('opcoes', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('protocolo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
